[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.20"
optimizer_runs = 2000
fs_permissions = [{ access = true, path = "./script/fs/"},{ access = "read", path = "./"}]


[rpc_endpoints]
zkatana = "${MAINNET_RPC}"
